Implemented docker container creation. Does not execute well yet, though.

diff --git a/container/Dockerfile b/container/Dockerfile
--- a/container/Dockerfile
+++ b/container/Dockerfile
@@ -10,7 +10,15 @@ RUN apt-get update &&                                                       \
         perl                                                                \
         nodejs                                                              \
         npm                                                                 \
+        rsync                                                               \
         tzdata &&                                                           \
     apt upgrade -y &&                                                       \
     dpkg-reconfigure --frontend noninteractive tzdata &&                    \
     npm install -g typescript
+COPY ./ /initial
+RUN chmod +x /initial/container/start
+ARG CONFIG_FILE
+RUN test -n "${CONFIG_FILE}" || (echo "CONFIG_FILE docker argument is required to be nonempty." >&2; false)
+COPY $CONFIG_FILE /initial/config
+RUN /initial/update.sh container-init --conf /initial/config
+ENTRYPOINT /initial/container/start
